apiVersion: v1
kind: Secret
metadata:
    name: newt-auth
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:79+jL86+tO8cHGbzaH33Cas11NeG+ab4Gxt6Px0=,iv:MVYM1/M0DAuHlxYvm5bgO0vUoWUSTHMjPbK9czuyT40=,tag:cNnJSiznopMTmaVUuS6ipg==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:iXUNy16enR+d9n0w0bLW,iv:c5QXPVSDaqnqiEhl9MN6+v6qIlKYnvjWYtfltOSZ0yk=,tag:yqC+RbRc4N8KhfOJA+zNKQ==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:IB2lrhxejzt2O66Vi3azNO9OeR34yFW/4hjVn1aU16FWZB+XWqlWK/qrYZZVRXZm,iv:D9klWnTEwrNafSHo+UPlMsh+ZWRkmYeT2gNbX1ik9Ug=,tag:BbJO2AsgjIIuNF52JcFwnw==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNWVibVBLd3lJaHh5cnJt
            WFFmc1VHRjkrdEVHdTVUVFlvc0hhUXBBbVhNCkg1aGZVZlA4VTBrWHRPV04vNzdv
            Ny9yWUtDelp4aldxbTRjUGNxT2RjbUkKLS0tIDJDcW01RDYwQkN2RDNFblV6Zmg0
            aUUxYlUzZTkrZlQzWmFJNVdHNE81VzQKBnarfKH8EM4b6ZVeviOv+gsfdzW64YEY
            sbWFa1Ussh0Jgv9tV9eP4aTdA2XDnxuq0FMElDgQXpb0oxPy0S9vdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T18:22:17Z"
    mac: ENC[AES256_GCM,data:EZGdL/sJPk9HpdpjrZldPOePrc1hw3/CfMoq35XKwQdnEfIH1GBq6R+cMizFQYbSLMmBMidJOfL967TUR0d93dJ/iggG0LoghmeLcZO009C0/hgufdSUBGbmG4B5I8Hc/tdjwb3NaDlhTaEJKQtLxYhguFt2jm0EpP/Vd8vy2Qg=,iv:rZ/ze2ngs55O5ZzHRV6e12kykMJekxvKlNZFe9Xaz7s=,tag:Bhu3I1f6aTa/W730VftPMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
