apiVersion: v1
kind: PersistentVolume
metadata:
  name: tss-pv
  namespace: tss
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/data/tss"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tss-pvc
  namespace: tss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
