apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: tss-secrets
    namespace: tss
stringData:
    TASKCHAMPION_SYNC_SERVER_CLIENT_ID: ENC[AES256_GCM,data:Vo4bJyqzrQ/r0fsqQVQOB+5QFI+0ehhR3PLb7UCJaGhk/INp,iv:/UJoHK2He16Nz/3BxT8tvlgd4YRTHlVOipB9JNrF0KY=,tag:CHFiFEEiOS1BS0H27cVcYQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:XE0Aye0LYg1gheaNVQfxyaxWQqzt6Mhg,iv:ZjWhG6HV5Xzz54pOdBcpH8lAbbydccaslXvXfAl+9yI=,tag:yKCPlAaGdQ1POzDaKRwd2w==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbldjc2lsYVd3MXNyeVdY
            SG0yT0EvSm5UejFTNVg3MDl6VHBUWTlvZ3prCnMraU5QZmNMVGtEWVA0NWtCR2Ju
            Z1orNUx0Tis1K1dGbjFTYUhvbDFNTmsKLS0tIEgwYmYwdVhHdlMzOW5MNWtOVWVB
            dXo2YWZIZmQ1K3p3a0tqeWdXbHFZTk0KUVu4PSMan12tE/tiTb0IRM6sRZB1bwlJ
            zKjndrn8Db0DLbDTxi309wMsUkqoGQnXnr0AgnyJvWX4Qm3jz3xirw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T22:34:07Z"
    mac: ENC[AES256_GCM,data:pqTdbeY8eWnxsenUI1LNqEPQ1wQ0he1oWhaUU03TFTWLqt+Lvai3Do1fYrBu+3QMsD/gLZurhM9nr+LqUWkpTPmnDGW6ClzEetrsuxz/WbfyYFMHDx5gOv3TPsgG4wp/F2Nuf7tS7HvToEJJ/O5ABHX+bHiWfhi26OL1rUJWQ/w=,iv:Wh52tjIxuqQiO3a3PNZYv05CMgpAtLRQxzxDn0v49RA=,tag:Z+iJK9eLuIvoR5QN8He7iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
