apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-admin
    namespace: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:3n/m57Tc31Ykh58UEdt4mjQCMjL/BuxkQEpzSKovbU/oyF6U9N71jF0xBLlnLQle+uo9iT1Vj1qK7D+xUHSbfeuCRaBZAF/lC2vbqGEL0LhVXgfbXPq67ZBZBmJokN2wClL4gnrI911+tsTd3SoY0uIxlyRoZA==,iv:f3sma6EIXmCQN81imURi4ZU5LWLLW4zeyGwJAMAe/1I=,tag:Apys2TpBVSdH0KCj//balQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:iDAeprEvLjYv82CWmvPa5QRC2pn/JT1MVLpelixrtby6BAzx,iv:m9tlHuDN9fyzJZexxm/zLxnMs38Vxvkz2PcygPnKxcU=,tag:JGcH+yfyHUYcAxA3IZRyHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSby9ldXM5Y01TbW00R1Bk
            L2JqcGNvSjdKRDd2Rk1Hb2tSNjg0R1cxMERVCkd4TjBJc1NyekljRG55c2trWGU2
            RDRPbllySjVaYk9yVHNTWXF3c1FCVHcKLS0tIElJQ05GOGdJanRDTmljZlNLbloz
            aWN3MzlvcTdwd1haQjdlZVFuNGZmUXcKyo0Coe8Jzb/h+o9oTFAAtJhD44WSfc0g
            VAHxX+GncniLCK/vAw0+/DwsqBlYmBGDzGqD5Ee8EanB+HCnC34Q4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T23:11:24Z"
    mac: ENC[AES256_GCM,data:oEvrPnitSiBRf9ZSnw7fAOxUi3V5YgOL37LxApslYHRNPX0nt5qJgmfbkWGDuDqhJ3qSkJK3v6JmwFCq1ahqfTvUVA31+VZDvM0bUvPEoN5hrrj0RtsBGrpbg/NuY7tw1MkDiGrNUzeG+kENMUZME6TUMAQx4yxPkTB2kNE8Z5A=,iv:1lVFSH+83vC0ZLxCoaLV9/d+j0+ROrpqU4PJGazI99Y=,tag:xzuaXfpWcAshQMyoBJc3ag==,type:str]
    version: 3.13.3
