apiVersion: v1
kind: Service
metadata:
  name: dnsproxy
  namespace: dnsproxy
  annotations:
    metallb.io/loadBalancerIPs: ${DNSPROXY_LB_IP}
spec:
  type: LoadBalancer
  selector:
    app: dnsproxy
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
