apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - config.yaml
  - secrets.yaml
  - firewall-sync.yaml

configMapGenerator:
  - name: firewall-sync-script
    namespace: frpc
    files:
      - scripts/sync.py
