apiVersion: v1
kind: Secret
metadata:
    name: frpc-secrets
    namespace: frpc
type: Opaque
stringData:
    FRP_SERVER_ADDR: ENC[AES256_GCM,data:qpWDTFsl+4CRJ2M9Cw==,iv:8PHLxsMa8fuLHEV2JzvyaypZ/T7LW2oV5KoJNe7ne0I=,tag:L+Uon+J7L70heQ285mRXBw==,type:str]
    FRP_AUTH_TOKEN: ENC[AES256_GCM,data:QL4wDVLAWnu4mLbjH1FFz/mFtLreO3WtcfQ4G/APei817Wuwht06M8F3wC9dbZscdi21w64q+8J4cQMWXVUGcA==,iv:hTFvR7/97xpWebkeNbJbAisXSDSOycvtwV+5w6rEKug=,tag:PhENwnKUsogxPC1uRq/LjQ==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVFBNZlZFVkY4SHVUVkhM
            ajQweCtrM1pEaWxmUWY4eWZBVVVmSVppeFJjClBXMnNQSWp1Q3FhVXY3R1g4YVRn
            RUswWnc0Q3JWb1VSeXA4cFNzYXBRTTQKLS0tIFlQYnRySlVCTEZDa0ZRUDhDL2tR
            NjM4QVRvTFhnclE3OU9WWHhrV3Rxb0UKWKvoFgU0OK5YukjGp2Cx97LcV7dq15RT
            MJxkjLbxmXZxad/wgyAM/S0hUvkSLdqogSIxqf358Thyg1+DduvqyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T22:55:07Z"
    mac: ENC[AES256_GCM,data:oaq/3CJpGqr6UMB4bMratbRPjxns7H4LR1pAsqA1JDbTo51UgfqrKjd47yIk7NaA98nLX4NDgkrIlH4meNVF+23+icWWLXMp6ta3ImAT8csKg1XdjDAGEjzdvkRxMu/SghE7ppW4ME/rwFp7y6vB0ej08Ihyg7niSEmBGICAk70=,iv:95RQ7fFQQqncuoV0mv+kWWjBV/nLWLnEjG+Oe3eJ3zk=,tag:SxkIe5/MAe/4Dh0Ojep4eA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
