apiVersion: v1
kind: Secret
metadata:
    name: frpc-secrets
    namespace: frpc
type: Opaque
stringData:
    FRP_SERVER_ADDR: ENC[AES256_GCM,data:qpWDTFsl+4CRJ2M9Cw==,iv:8PHLxsMa8fuLHEV2JzvyaypZ/T7LW2oV5KoJNe7ne0I=,tag:L+Uon+J7L70heQ285mRXBw==,type:str]
    FRP_AUTH_TOKEN: ENC[AES256_GCM,data:QL4wDVLAWnu4mLbjH1FFz/mFtLreO3WtcfQ4G/APei817Wuwht06M8F3wC9dbZscdi21w64q+8J4cQMWXVUGcA==,iv:hTFvR7/97xpWebkeNbJbAisXSDSOycvtwV+5w6rEKug=,tag:PhENwnKUsogxPC1uRq/LjQ==,type:str]
    HCLOUD_TOKEN: ENC[AES256_GCM,data:IO4WlowMcty8M1oyf9ha99bLQJeEddNL4VgMNPsKoe/XYT5Hma2hWKmuzg8fJ40Vr9VhycHVtzsSqc87mrnWwg==,iv:bpEuIB7wW76IaV4VLPc14GydqrQ3XkjOiCrqL6Ed7g4=,tag:PGZiR1AUuKrwkLZX7CCD0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVFBNZlZFVkY4SHVUVkhM
            ajQweCtrM1pEaWxmUWY4eWZBVVVmSVppeFJjClBXMnNQSWp1Q3FhVXY3R1g4YVRn
            RUswWnc0Q3JWb1VSeXA4cFNzYXBRTTQKLS0tIFlQYnRySlVCTEZDa0ZRUDhDL2tR
            NjM4QVRvTFhnclE3OU9WWHhrV3Rxb0UKWKvoFgU0OK5YukjGp2Cx97LcV7dq15RT
            MJxkjLbxmXZxad/wgyAM/S0hUvkSLdqogSIxqf358Thyg1+DduvqyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T13:56:23Z"
    mac: ENC[AES256_GCM,data:T8YhnMrFV70U3mhTX8aTiLLlJ6ccjxdfJHD28fz6ic6YqKvCLK8m/wiQW+H0hCsQ2SPkM8KnGjMDlpZ4qydyXMobIUcSsuqedaUJcfzX48tt2QKu+O8uuwR6kTOvIDKoRe4H3paUcta9hbBzVuFn+UwFpMM5EH0Mitbx0A2li8I=,iv:W10iSULPXg4g0cLEiWNZl9FcxUInoZrA5WjnFBZPHbc=,tag:Q1cXkxnweIoKU/P50bYhXg==,type:str]
    version: 3.13.3
