apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pv-pvc.yaml
  - ingress.yaml

configMapGenerator:
  - name: ntfy-config
    namespace: ntfy
    files:
      - server.yml=config.yaml
