apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy-pv
  namespace: ntfy
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  claimRef:
    name: ntfy-pvc
    namespace: ntfy
  hostPath:
    path: "/data/ntfy"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
