apiVersion: v1
kind: Secret
metadata:
    name: linkding-superuser
    namespace: linkding
data:
    name: ENC[AES256_GCM,data:GZ8fEGkSHBA=,iv:kBIEsFvAvtLX1PPWNvNrpJc2Xi4saGEryececYZnan4=,tag:ICtcVK6Iu82ZwOYdRW5xCA==,type:str]
    password: ENC[AES256_GCM,data:NUF/NOSN/TBFztdByUhNyAdgUvYKF8N24XjXTjx8MgQ=,iv:z8RhcX9gK3Yn/rmGMzNE/+LaSczBG3jkeG0prkNog74=,tag:rxo0+39kSyMPt/iWdJoT/w==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd1ZCZzNhRkdidzhFc0NO
            aXZoYkMrNmhDakdIcEgra0xhbVUycVRpcndNCjNrZDAyZVU3Q1N5YzhCUXVLZm9K
            bTBtVGRDVWNKUlFkNEx5NWlxZmFPZ0kKLS0tIE9Dd0IwRmxFb3JoUEFqRE1xaFVQ
            bG5XcGV3K0hmUW1QbXlzUWhWWVNHTGsKm344KlpJGlrSNY6K6dUfSCVcLOqOYo1r
            vAQ0r+Y6jJQufmfvTxxiKzqRpOK7GpNRLcDsn187BLHx6FA6q9h2hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T20:38:32Z"
    mac: ENC[AES256_GCM,data:eeboQNmjV7fevMgFA2pWi9XNTvIUhVi+xHNqUB8xLb2RUYlJk/6ZkvGQSMTIkNRkXXRSg8dsjFYVUutqjks5CwehjdiO7+24BlLrkFJuEJSk0UbIlwCWi3e0HJ6SUCOIOpaZRp7d8W7RhudC5rwTwYNJU/U2LU4eRJlV3RRmPJc=,iv:bmUjET+B08BWxYPqdZJResXvWPzRh/e4z2zTVo2iNX0=,tag:QciNdgYbVBw+27RGbA8tig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: linkding-oidc
    namespace: linkding
stringData:
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:cs+0qW6z1wpkwWRcsL46cKg9BuWAigEAKG12cOPmd3Z/yqow3eDQlIiOQ1jzM/qfXxGZ+2i7FMwTeC0pPpNTSQ==,iv:W4ehM4f6iwrC9qIsyBQwb3CQ4ppPlwRj1HMETb4Ugms=,tag:+fUn83L++76WE0yFfGog+Q==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza1RnRWJVcWF5SkJhVjhK
            MXNna28yZ2R0Wm9LcGdaUWowcFNmOTc4SG04CkFnMkVUYWdBTDBjcFRuUWNCLzd5
            ZUxNQmsvNFZ0ZnFwQXhLS29kN0N5aVkKLS0tIG1mUzhhYXFRODV3MVhXVmtBbkZG
            cUxtQmJSK0E3ZE42VXo2NlE2N0pVZmsKArXu5a2gOCNEfGzip0aDlZaUDfHseKJX
            bWzOJ6rx9rjTIhjfWH/Z3exEmP3b5fOzyEeiJ4MJIhfD2k9zzgn/aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T20:38:32Z"
    mac: ENC[AES256_GCM,data:DChyx7wcr9j1NmZh2vb1V5f4zsAil4aU4TPrB2WgcXtKn6GhV4TFzU5P8PsRTQV+0hsPaOkANBT8d2LNkThAcH62l0AgIHKSv0kUuOqG/t0qy3CtJTi7awT1C6J8x8IZWjAG/oWDlgkpTg5S/LmRexyb+PQdLLW8HnJgxzbQdJ4=,iv:p9z2753nhwVcPLvIM8noGSNTK+N7aphxt8+sCMA6c8w=,tag:WtqWBnlZiQ8tzov6WBt91g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
