apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  configuration.yml: |
    theme: "dark"
    server:
      address: 0.0.0.0:9091
    log:
      level: "info"
      format: "json"
      file_path: "/var/lib/authelia/data/authelia.log"
    authentication_backend:
      password_reset:
        disable: false
      password_change:
        disable: false
      refresh_interval: 1m
      ldap:
        implementation: "lldap"
        address: "ldap://lldap.lldap.svc.cluster.local:3890"
        base_dn: "${LDAP_BASE_DN}"
        user: "uid=admin,ou=people,${LDAP_BASE_DN}"
    totp:
      disable: false
      issuer: auth.${DOMAIN}
      period: 30
      digits: 6
    identity_validation:
      reset_password:
        jwt_lifespan: "5 minutes"
        jwt_algorithm: "HS256"
    access_control:
      default_policy: deny
      rules:
        - domain: "ntfy.${DOMAIN}"
          policy: bypass
        - domain: "notes.${DOMAIN}"
          resources:
            - '^/.client/*'
            - '^/service_worker.js$'
          policy: bypass
        - domain: "links.${DOMAIN}"
          resources:
            - '^/bookmarks/new\?' # used by the ios pwa
            - '^/api/' # used by browser extension.
          policy: 'bypass'
        - domain: "*.${DOMAIN}"
          policy: two_factor
    session:
      name: authelia_session
      cookies:
        - name: authelia_session
          domain: ${DOMAIN}
          authelia_url: "https://auth.${DOMAIN}"
          same_site: lax
          inactivity: 1d
          expiration: 1d
          remember_me: 30d
    regulation:
      max_retries: 3
      find_time: 2m
      ban_time: 5m
    storage:
      local:
        path: "/var/lib/authelia/data/db.sqlite3"
    notifier:
      smtp:
        address: submissions://smtp.resend.com:465
        username: resend
        sender: "Authelia <auth@${DOMAIN}>"
    identity_providers:
      oidc:
        jwks:
          - key_id: "oidc-key"
            algorithm: RS256
            key: {{ secret "/app/secrets/OIDC_JWKS_KEY" | mindent 14 "|" | msquote }}
