apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-pv
  namespace: authelia
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/data/authelia"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-pvc
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
