apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia-valkey
  namespace: authelia
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: authelia-valkey
  template:
    metadata:
      labels:
        app: authelia-valkey
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 1000
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: k3s-2
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:9.1.1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      volumes:
        - name: valkey-data
          persistentVolumeClaim:
            claimName: authelia-valkey-pvc
