apiVersion: v1
kind: Secret
metadata:
    name: paperless-db
    namespace: paperless
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UOrxtXKOFrADu6Ew12r/1H2UjZS+LXnVzpyukDlnSmNASbJzOid5rL5qNA==,iv:BtqIZdWoZxX91nHrms+dvKIo3GPzVjhLJP3dBhpb1pI=,tag:EA/9vOp8C3IuBwWYG2nl0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY1JtN2Y5aTJBTlM4U3Qr
            ZWdhSzh6Nk5sUUk5bERaNUY0SlpNc1k2Q1U0CnNVSStBbi9XWldsVUdSWnlWVUNy
            VUlEOWttTjJRZ0pMZ0ZQTkNzZTQ0bmMKLS0tIHZKYW94QUEvbnFlbWVrUTNmS01B
            RkFTeFRrcURkamZGMHBhelRQZHMyMXcKMtmkh1TbetV0ULf3Nl7lnznS8LDA2B9c
            QB4ViLqbfQpChKpzX6byxDUl+BIA6HZAaVw9Qcr8+wqsDnosHFHCTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T14:30:35Z"
    mac: ENC[AES256_GCM,data:W6Z6PVBsys9Fc6MmzKnoVuxh1jFAZti2thOO7ocVDiuONVGxwR74TTBhbypOCpHXfct6tQYIglOOei7FHg9nb30wZaf81+MUGTt9eZVK1uIo3+85Pe6ronSRxj44WspUENOHJYck1bVA1HGjsoRXyN0BlBUOBRquGCwMSojEl0I=,iv:R1Nf7L0lXD0rtOgwAHJCHybIZCqiVkzRSjfVdw7qsFk=,tag:NhAYCETkgYdlwN9EoFGB1A==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-app
    namespace: paperless
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Eu6YVGTr33Coj81pnG9DqXi0qEbSTOhN5veqGZSfIQivJHrJKfCgsQyfDmUl2SeQp3Dh94a+dqfKT9hQn8SGAtWUtRjzByZjsEAW4oTckEihpZsMC6M=,iv:69wT6cZleVla5pk/FoZp0SmTYq0k8S7gT6dGYHoLup8=,tag:zeHoSco8zFiHNJ+lziReYQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:Z9NtWg==,iv:RGaL88V4bH6PcTZmWV1EObu25bgIlSRThs2VkvwQ0NU=,tag:RCt+Wnu/+Sdm8xQM7JguXA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:lx8YO0BfY0O3tKJIJF5fOMGnX0PIvh2WPMXcv8EawQE=,iv:Ip3xRcXYjcEgv17oDVX69qhanRKJAHIkeob3jJqmJ0A=,tag:VPozPAwvkY1HQVh5aekMlA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:wbDJ0CcAjXqmrs33RHYx87MMv8MJvlsxF2yb15o0EjEAQN8e2JJ24Khl8MQ0JTPzZPsT7m3he3GIs822MbAoOA==,iv:9Qfy2YRdO3hZpHIcZnYKwsckTvvD1Rtrk+I9Q3KYh/A=,tag:fhHZ8Ng2eqOGLDiFp8B/ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY1JtN2Y5aTJBTlM4U3Qr
            ZWdhSzh6Nk5sUUk5bERaNUY0SlpNc1k2Q1U0CnNVSStBbi9XWldsVUdSWnlWVUNy
            VUlEOWttTjJRZ0pMZ0ZQTkNzZTQ0bmMKLS0tIHZKYW94QUEvbnFlbWVrUTNmS01B
            RkFTeFRrcURkamZGMHBhelRQZHMyMXcKMtmkh1TbetV0ULf3Nl7lnznS8LDA2B9c
            QB4ViLqbfQpChKpzX6byxDUl+BIA6HZAaVw9Qcr8+wqsDnosHFHCTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T14:30:35Z"
    mac: ENC[AES256_GCM,data:W6Z6PVBsys9Fc6MmzKnoVuxh1jFAZti2thOO7ocVDiuONVGxwR74TTBhbypOCpHXfct6tQYIglOOei7FHg9nb30wZaf81+MUGTt9eZVK1uIo3+85Pe6ronSRxj44WspUENOHJYck1bVA1HGjsoRXyN0BlBUOBRquGCwMSojEl0I=,iv:R1Nf7L0lXD0rtOgwAHJCHybIZCqiVkzRSjfVdw7qsFk=,tag:NhAYCETkgYdlwN9EoFGB1A==,type:str]
    version: 3.13.3
