apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-credentials
    namespace: immich
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:FNDnGIiQ,iv:FrotqoAPi1lUD6YROJzJFnjinKmKKO+fmMP5ztUNkA8=,tag:K9d6DSZKHKEFYfRz15vGeA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BIdsM9Tx43DeNA01hQHYaoe/ym9mUop1SSb5pUirg5Q=,iv:c6VpjLwhKiniGFu+lTQ9h0x95mFaKp22/71f4FO77gA=,tag:Y+BUJr3dGTNhNQE9rrocQQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:5eqpnDIp,iv:Y0NeEZr+aO5qXemu8GsNmYl0QQtQGJAAz/LKEAG9TvA=,tag:+QtxzyxeMh7588IWwRoeyg==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQVJIV0xDbjRKaUsyc3pG
            bGhjV0VCYXdSTUJrUnZKYlVVeWsxODZOcWprCnBPbE1qWUZrYkxCVnk3MkVtcHVI
            ZU42UWFTSWQ3VzYwRFdKUHgyYmFIQ1kKLS0tIGdFc2Y4dXkwSkU5bUZVZGlNTlJK
            bmNpYU9jOWpUbU9UNzJKSnRDTTNmdXcKdocBCluDOmDFvd99tGWU2ZPKIy0GKeeB
            j8thdaB1ALH5u0eqRvwUXGsMDd1ijD+sYst/tDvhiVRCJ5pZkeyp+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T20:37:43Z"
    mac: ENC[AES256_GCM,data:+Ro6juaU6ly1FK+Ap2r15sSgw2N8bCp/sjSAzJsh05d0gDKapkzreDQp0vEoMBZgGnrbcwxx91lXA3Ma3MQHkN7OgVOubfEYLKNwTD+ivCgeviGxqZzjJ7Wy8CiNaDZFyBC7RqD760/mHIuFWjoqe4mWWLYMXrIMLMqV8xXRxGI=,iv:B2hNNxs8rIOK2PNjDkI6KEsshEzI8fiIvDgjNb+ME/k=,tag:g5DuMglSJLgetG2tf/5TuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
