apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:XGjcNMIOo3HMum8EWugb/Qld2MqKRK+7zoKXzGLy7mkrTezqhEaE0i3r8gTMMc8Xhn3aOLf9Q/e8HTN7fVw3cw==,iv:oONFD70jXWTeDHUeCvcxaIhNgVaKWo6/D9yknzbmF/Y=,tag:sOgFbAt1RPaBOldGBVtlNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdjF3bU82clI0UnZmUnpW
            bCtrMURiUG9SNWJOcjQvTjlUZXBhRlYzZ21rCkZUS28rSmpKeFZ4UUp6cDNXR1pk
            WWxIUEo5U09kM3o5aWpScis5bGNDNncKLS0tIHhJYmQwaGdMZENNQ2xURkIxdzRh
            Mi8zOUM0REJIWEQ2bTkyWWJGblA1RTgKbEz4kye0LV/w/25WYci9q5QofElrRBuq
            nCI4eHbshYKFWGjZBIvCdfT5yUeGrul4FTN71J7xAZcI5b6Uua7bPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T13:28:50Z"
    mac: ENC[AES256_GCM,data:LVw8dhXiF4cIBwcCUOgTu4ymWbHkM3atbLI6Sxt1GJ/t2oezLwZLyaF6SCy9HNaobIoF+MN2fUpFvDqdpO0fuYnXpRmBkdFrkNaWWTgFj7Y4EvZcJo+q6vgjfHnbJy23SIt1YENh1onEobi/vqY6XEV17OBtDg2fjavDBL9dZMg=,iv:PvOy0yupFXTFTUZCTUP53WFz1PzRLJ//P/yJOP6pZkM=,tag:YiX+StS1SspAM6Yt9qddVw==,type:str]
    version: 3.13.3
