apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
    spec:
      restartPolicy: Always
      containers:
        - name: lldap
          image: nitnelave/lldap:2026-01-06-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3890
            - containerPort: 17170
          env:
            - name: LLDAP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-jwt-secret
            - name: LLDAP_KEY_SEED
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-key-seed
            - name: LLDAP_LDAP_BASE_DN
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-base-dn
            - name: LLDAP_LDAP_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: lldap-credentials
                  key: lldap-ldap-user-pass
            - name: GID
              value: "1001"
            - name: TZ
              value: CET
            - name: UID
              value: "1001"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "256Mi"
          volumeMounts:
            - name: lldap-data
              mountPath: /data
      volumes:
        - name: lldap-data
          persistentVolumeClaim:
            claimName: lldap-pvc
