apiVersion: v1
kind: PersistentVolume
metadata:
  name: lldap-pv
  namespace: lldap
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/data/lldap"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-pvc
  namespace: lldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
