apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lldap-credentials
    namespace: lldap
data:
    lldap-jwt-secret: ENC[AES256_GCM,data:3CHPgNXFeLcGaGaSab5+76Akk2fexm9rT8V4xfvyZMJSC7m2PNNDoCyoRD6m45gAZkEHM4zwEwWQPwG68aaqB5CwtaiLkUB6p/Irv5BJaLgN/rZ06gSyh8aI7yJX1N9eq2aKfUcbU/lOD9zOlZ+QK5WGw2N+V52s,iv:9vYGIvkLxek3yPefWNhvbTAbHV8kkaF5/K3JzDBxsFg=,tag:K8AMyoEYOzZCDCYfCzuXfg==,type:str]
    lldap-key-seed: ENC[AES256_GCM,data:oJ8EmEL7FjUfCXLF5er7fO8y0bR+uoVZ6NP3jK0toUfuNwI7yTm8Iadcdia511Nu+zbVojU0nwO3EzGJ/2LptVUXcWdtMidZJ/G6CuaHE4szj4ecIg4QBg==,iv:RC740urLtCA94Nu07oO5RkTbo+KJK7aK2W5iG0u57nQ=,tag:zZLVeCkfgzG1MqHwTRu36g==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:peQbKzqJxYl2H8+RWYhug00i075MWnCHUG5r9qO8drI=,iv:ZTYuHg17NPjAUtQwbnVD1wqiSjjZvMj3UX2t0o1gseI=,tag:+umizRgfDO3uE3fL1i1wWg==,type:str]
    lldap-base-dn: ENC[AES256_GCM,data:iRobvLfD2Qr89NXtw52B8+Ux+L4YQSs/,iv:XTnrNvIKyh5HXuiirslTU0OpQKFdJMpLiqXI0J477wQ=,tag:ArMNQUUKmBNZfUOno6e1vQ==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMVVqQmx0VnFLWFpBNGRw
            cTloL2U4emoya1ljTE94eWRBR2piV3dpTEM4Cm05R1FEWExGaXBlc3BCT1VIdG1P
            VVZUWVRzV2hWSEJONVBYbStIVVM5czQKLS0tIEh6UXpmdEszb0tEMWVpQkI1N0pP
            VHVGamUwb3BPcnpBWmJ1aVlmVE9MYW8K0EmLMw09gRkyWhDRze625cZ1tjf3v08f
            hJ7larUFjXtU78KXDUxyUf739wiI62/EJzD1npTy5Q13/s2lDpMd9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T00:06:23Z"
    mac: ENC[AES256_GCM,data:xxm5QNzLOMDlexAYXRBLxkRnSdNXvIvLuK/bbbICcSx+bNMzq8V5Xr4CjiJqWnSHZDnjciPfl0AxOfOC5ScSkozS5ZqgGPilugr1sSh9oqVhdlGEf+imCIhqqBriIHETMISbGBIGCZOSfihFBboQtl4ee3McDzWk0Jsqwf680TY=,iv:3Iu+PguB8V8vBm8lPP025VjkXbIqeps21N7T58MkK8w=,tag:Jp+YRQIVJMdDkT9e6jMY1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
