apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lldap-credentials
    namespace: lldap
stringData:
    lldap-jwt-secret: ENC[AES256_GCM,data:Mm+MsMadxSwr76nnwm7oJLLd3s1seNpCObKifRjCW4CCC4YL4BH4Zmc8U0qQQqpKaP9m2YuW8B1J8cW/8NH2VK+Tp5ePsJKBPQ2XcDmGmMheI3BdTWPyvQ==,iv:gVnNjGc4uzNXQGJjZLf3cheWdVLDLuEhxqxa4ddGPdE=,tag:0WucOxyXesZJQxrxkA+USw==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:u9hlhdszzpbfeFfcYnsOhvpB/Bq/GXU=,iv:q2JLy6UWiCZ862DR0QIP5HkzKnEKXuqYe1WHumdpsZs=,tag:hOb/wRbJHxZhO2+x7e4xuQ==,type:str]
    lldap-base-dn: ENC[AES256_GCM,data:zmoXOSpoqbfOzs4NmUomBmcD,iv:wHp9KKWIY2tZRSJ1QnDr79nB9EKt6geGoEkE1LN4Gh4=,tag:MypmNCrYzy5WmCgpluItHw==,type:str]
    lldap-key-seed: ENC[AES256_GCM,data:qcS4ZGi9yqD/N/gT9YoKZo1AsTBUysURK3xYixIAFNz2V/qaAc6IFu3jTOhcEYCki2K8+crBAmd3WpK0D6foyg==,iv:0BNQ6x7DAg/UuQtVkDj80DNmHkqZq6wIljulV3+QeCM=,tag:2b9236PkYOoXlrdXZy+aAQ==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMVVqQmx0VnFLWFpBNGRw
            cTloL2U4emoya1ljTE94eWRBR2piV3dpTEM4Cm05R1FEWExGaXBlc3BCT1VIdG1P
            VVZUWVRzV2hWSEJONVBYbStIVVM5czQKLS0tIEh6UXpmdEszb0tEMWVpQkI1N0pP
            VHVGamUwb3BPcnpBWmJ1aVlmVE9MYW8K0EmLMw09gRkyWhDRze625cZ1tjf3v08f
            hJ7larUFjXtU78KXDUxyUf739wiI62/EJzD1npTy5Q13/s2lDpMd9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T16:43:35Z"
    mac: ENC[AES256_GCM,data:FbT/3NP7cu3KXW86YkCD0mOJWITODujQ5FrihBMPvvbbr/h8p9Ktb74upuHHKPU7EEfEKll+u5wkvBcq78J6Hw3dQedQEeMoMv/svjJRwnT3jlJeTx15k5HE48Rtx05BgIbDk7hTcrcfPo20TSy/PoVR52wEQG1R6jGZJyKRU9A=,iv:vXk7gUF8HibZCmzaoKoAcoY/sP+1uE0eK5QlXPh2xUM=,tag:9cPGW2uc3Tk94j4f4zKTXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
