apiVersion: v1
kind: PersistentVolume
metadata:
  name: atuin-postgres-pv
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  claimRef:
    name: atuin-postgres-pvc
    namespace: atuin
  hostPath:
    path: "/data/atuin/postgres"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-postgres-pvc
  namespace: atuin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 300Mi
