apiVersion: v1
kind: PersistentVolume
metadata:
  name: atuin-postgres-pv
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  claimRef:
    name: atuin-postgres-pvc
    namespace: atuin
  hostPath:
    path: "/data/atuin/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-postgres-pvc
  namespace: atuin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 300Mi
