apiVersion: v1
kind: Secret
metadata:
    name: atuin-secrets
    namespace: atuin
type: Opaque
stringData:
    ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:nmMzkbDLtrsS9aFMvoYOGv6OH0HkVHNIX+FbOogXz8w+2d+tstpgBSpYaiWPMrj4snCK9IJAeL1nGB/snsSFRA==,iv:yPNfOTor/xbDbSzRK311u9FLhjFYW2P2uHxQHAOgSow=,tag:mmWVwoZUoSrk4m+vDvHUiw==,type:str]
    ATUIN_DB_URI: ENC[AES256_GCM,data:L8z7Qn4jPQ+oMi9kuNson31rE/qEbdVeTtUvRuR7X37IH4BqpBYf/4jPvcicndkOoODPxb1FtrUzHNTglg4rIxuEPYzCnWbm/KR7KOLQvDmC4MJcYLugXq/5m52dUBJRYSFIwZ/r,iv:h99I1pGr6eu6HtNIeKFUOzmaNRp5TWhmqeqSYPZJaBE=,tag:dkulhNeJyefin55OCdklrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQWx3ZW1CV3dHYmxoOEpO
            K1dPNzZ4akV3SGhNK1lTYjVCaUp1eFE4VVJNCnhlVVZQZ2h3ZGh6cW1CYVd0QVFq
            Tmx2SjBNUjZiMjkvcDhOakpxWmlLWDAKLS0tIFo4dWxOQ3dWZHBmQ0tkRlRuRnIv
            bjZEVUlEVXo2K01MNE9PdkphY0NNM2cKtBcuQPDOcoTsu3O2+AcFN51ooY8RayAJ
            6Bfi8IXy1PuWyETGzTT1kW95hUKFLwNY+/CnwSrAowaodTuFU827Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T20:05:47Z"
    mac: ENC[AES256_GCM,data:DlcJPb+MsgF2svnNTCR4cV8ZOmO6DVpeMUAnGoMZ2ZNqkavX6aGZfLIp1m1MIgJ0YqSKSryE8nDRgJdSIZBJC9WP1esSwnWnSmQ+rkLExeWcYC6MbhiYGjvEV5wYEOHImgn7cpnyRw2gXCW/EmRbp2IauOZciPyRjFzmbAd/+00=,iv:7+vKfwKIqZ/ItFjspAWZbmOs0TvqkwNlYhftr/Y7XQs=,tag:D4ey7ZiJy8BgFAyUpYaBvg==,type:str]
    version: 3.13.1
