apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: mealie-secrets
    namespace: mealie
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:9gseq8CAIiIXFwZTFEko4FJy2TmTE+pv3gnhxRlLlJiHdeunI4ISfmZracfJaKeod4W1B9Oinn7BXIMAXFGzPqxMlJGb+e1W,iv:OwJM7JMSdpJTS4xaEDhoRfN3q1nBtI812Ov3zM6gtR0=,tag:RILz90lBiVkH+R53HWiRTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eDZPT1NTLzhHUUVSdkNI
            V1ExcURJNWlhWkt4ZkhTb20rVGRReG95ZmtRCkd3ZmV6R243eWYwV25ocVZQWXRt
            THBmamlpb3JWOU0zdkxWSDBkakJ1SGsKLS0tIDA4OW1FdWZmRUlpR1ZuOUlDYWR1
            eFkvZjhKbkRBRzMvRXNLWDNTbG1oVzgKW5XivebBKIscIGNAaaNNU0dRpYVoSm8b
            uydk7t/2prcJgZU/R4pFSkHeeANuuKC7TqNb3hl4wYhhI02xOmR1Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T15:55:30Z"
    mac: ENC[AES256_GCM,data:Ksr5ibuHEDRrx7w0TEoDMic5vJPniNNRDT2qg4GW/cmRogkqKjSDuOZKodYScU7cjXlYHiyCAw6NfgATI2lR33N/I0iYm9DSXN6h6wKwjUY3ZKAop7tl6oNu+LyHiTCaS/knYNb1XKEi6puaKZePpz1DQW+d4AWnCg9N0YN7DS4=,iv:t7O7tBKKIfF5wVHzu5poSj1OEPJx3sPmO6Hq4RSflek=,tag:/8tGU8UheQZwYpy6CEoC5w==,type:str]
    version: 3.13.3
