apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/traefik/helm
  interval: 24h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  type: oci
  url: oci://quay.io/jetstack/charts
  interval: 24h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  url: https://metallb.github.io/metallb
  interval: 24h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  url: https://kyverno.github.io/kyverno
  interval: 24h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/immich-app/immich-charts
  interval: 24h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fossorial
  namespace: flux-system
spec:
  url: https://fossorial.github.io/pangolin
  interval: 24h
