apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "39.0.7"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      tag: 3.6.13
    additionalArguments:
      - '--serversTransport.insecureSkipVerify=true'
    service:
      spec:
        externalTrafficPolicy: Local
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        memory: "128Mi"
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
