apiVersion: v1
kind: PersistentVolume
metadata:
  name: miniflux-postgres-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /data/miniflux/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miniflux-postgres-pvc
  namespace: miniflux
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
