apiVersion: v1
kind: Secret
metadata:
    name: miniflux-db
    namespace: miniflux
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:pwHn0mXFw6U=,iv:xa0SZHVRdw+kRgIIs7PfNI6tgxu8q52f00lS0uDC5uk=,tag:IGL1aSZTNlh404IR+heD7Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ed5f9SjkWjHBEMzSdd9b6bxiFA4Y40VttqHiSvXySpTQtkcBI7eEnjk5RJIRG90dAzJ2cni8zRrJ9K4IbDnnYA==,iv:Lokib+qChlFlWoynYDrR17Hx7JZkkPpjzVHPqbm83Cg=,tag:BCbUpxvDPcgivyKHr57VKg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:w8acn4CgtF4=,iv:NvJdE+AR3rXNjAq0dxUoutXTR9Cpn7mrdioa2NW7xbE=,tag:TUjKIJgeyNYlWI+Nr2JbDA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oPzNiXchWn3lmuxl5S7L1/fR4dn8LZs/qxuCr78Pz/P0nMH6Fg4oMW9XxPtB3h94csv9rtN4stWmAe3wwu6/IR5RCb23IQ+7zm4h32ZqF9rbVMI8MMSsQXvGn8Pqpkzsge4JjRzHx4LVQLI9R9FcgUUMlNife+7JyiICRi5fEw==,iv:mApKW5Haxn32Qs3iTUI7gtooB1ez+iOoRj5toiegdu0=,tag:SBE060/hra09GmEibQPhuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd1NJNnhPU1FDL0Q0eUhO
            Znl0UFpCZ3d6NnMvNE9uN0xQemFoS0prSHhVCnJRdnZqTm5pNitTVERQQlhwN2pn
            QVlESXZ3M0YwTkZqdXhFazIvK1luWkkKLS0tIFozWmN0MnRVYlNxTEtSS2kxM3dy
            UkhSMXd0UXpCUkxaRnlBNExveStsNDgKqvFR/1Z7KOD1jZr/m9Fjzua1pyd+Lm1j
            hp1vHwoMk0McJDc4oiUbmYaWXxinG31TJnRmIoEAZDBajiVc3w3juw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T17:48:42Z"
    mac: ENC[AES256_GCM,data:Iihv8kYHf7BT/+E+9AYHTi77n+7O+3a1bwO7jx5xCFuOHue1YPmxKJ+GCoCt4PIPDuhU13nLNwu0AScgKvaVVe3r+Yi0sAT4GZGxWIuSIlNmpKC3AeQzZRzPT4qqw3MWrzwAkzUTCQ3YT+i/MusndsDs072Kij/J812fCIS7tKI=,iv:10kRfrV6od4WpL3AbCDXZd3PAbDR0CgtRSm7BD2N2ko=,tag:1c5f2fCoM3kugqv4YPCpkw==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-app
    namespace: miniflux
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:AcWQEmA=,iv:oSj59pP4lF9EiZAokw7AnVRBxBL4Z4BN2gfRnr4jZdw=,tag:znyg6MevBJMf15EJ1gTizA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:EG9UbMg/QOkhqOATwHSNQajGmg+iu41spDdp/ay9xZmiYHvYU8sjkfAbs5aSZOyZg9AITVTRxTeGifg4bjvUVw==,iv:CvL1CRJqoAEBgg7hBz0fXfp8SBfB70CeWXa7Hqkb250=,tag:PciTtK4Why5VzjbxJFbt2g==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:MmF+POuJPZ8meDilV1sLNDcTfQOlRBpxzoKgmwL4c070hrREG/RHx/7RX9SDnNx5vqK7HpMg2vo7fkw22C3Jf+fpK8/Ifr+t,iv:AoiyVesHj7MeblGzLWlTsOdhniLZiFvtgRh8njmVysk=,tag:EIBMywGYTUDX7hsWFtt7GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd1NJNnhPU1FDL0Q0eUhO
            Znl0UFpCZ3d6NnMvNE9uN0xQemFoS0prSHhVCnJRdnZqTm5pNitTVERQQlhwN2pn
            QVlESXZ3M0YwTkZqdXhFazIvK1luWkkKLS0tIFozWmN0MnRVYlNxTEtSS2kxM3dy
            UkhSMXd0UXpCUkxaRnlBNExveStsNDgKqvFR/1Z7KOD1jZr/m9Fjzua1pyd+Lm1j
            hp1vHwoMk0McJDc4oiUbmYaWXxinG31TJnRmIoEAZDBajiVc3w3juw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T17:48:42Z"
    mac: ENC[AES256_GCM,data:Iihv8kYHf7BT/+E+9AYHTi77n+7O+3a1bwO7jx5xCFuOHue1YPmxKJ+GCoCt4PIPDuhU13nLNwu0AScgKvaVVe3r+Yi0sAT4GZGxWIuSIlNmpKC3AeQzZRzPT4qqw3MWrzwAkzUTCQ3YT+i/MusndsDs072Kij/J812fCIS7tKI=,iv:10kRfrV6od4WpL3AbCDXZd3PAbDR0CgtRSm7BD2N2ko=,tag:1c5f2fCoM3kugqv4YPCpkw==,type:str]
    version: 3.13.1
