apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
    namespace: cloudflared
type: Opaque
data:
    cert.pem: ENC[AES256_GCM,data:fHMFhBHmaI8nI46xVwEugsrxSbIk+LM15dWGZ5t1br4hl4xZsKANcertdQmvwUSZMjZ8U2+kVN/q4q+7YdYCytgSkh2DX1EerD9Io3EthYOxK0Hg3AbdVJ9o6luBKmREe8pVb+rBUlOa7Vj2iiPQEIzezbAJUPeO7c1GOnXaBuF3CbbYfvaMKUzmTb9SaEfIT8Q5QgTes5saN6d1m9h5yOVPVKhlDgx4l+wDcIXLqE15q3NZZjoX8uSyaUyPyBg/YYmG7MRl3Y7wrkeUJijBkKqty7k86XfDbpaC5XLlKak935nWhY2AJtFZQZwMS/e/NP16KyaEd15HxtcEaZdUCP6ANPJ8N+raHhiwIBObqUvdIhDyipkP+3i/qafQXQJkFSh1BDoVGIH+PXwJzjru+Gdc2febLIMzoWhFI3N3YgAXoIAH/6piNocjfxoG2S6NdnKKMHAsSJVBLA/3YzDCs3LlMhU=,iv:RWGyQ1H5ZjqUHiKt9aXQVFgzVhGwRZsfE9YJBFCSd0w=,tag:oVtTjOumSq3Yu621wghGkQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:qUIMH8pDqHjB0hly4EZEgT3dQ7LNSjCoY6WcLluOMqXHGZaaG+sfYGrWl6XWRKV4IlgV8z6JFzydqm9sNDKmRmWAvCJHL9oTEhBlxrmTQbSlJfKwY5F2mholFlMroA0RExveBJ5PZCO7rOTZplvq+QSVEidZLoHnpYkQ3F/ZqwhRT5Oja0yC4kBu/zctMinrJg6rN4ko0Lje/kd+d5GH7sBQTg8wcaib0WWNObbjQj+WOnnmGpd6ct4WcV+qR4YB5I9JS5uaAteAGarrJAT0LNwfnOka8HDAJBIEyyaGfY5CWCEvcW1QAkSrRko=,iv:55n5DvLXLuvXP3lWOv9vcXAexMI4oTeUSS+lI42WjGM=,tag:zVJmyxY0aLvqtrWWtCnQoA==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cFhBcVNyMHFkVnNEckYw
            WXgybXZvTDFCVVpSZ3RTZDdhR2pwU25jZm13CjRSNnd6d2dneW0xRm5ha3ZmNjdj
            L25uTTZYVjB4TEloUCsvb0tjVFFabWcKLS0tIG5UL2hwMXA0eWFQUkhraGtsTXZ3
            ekIyY3ZxdHF1NHc2ZTFmQ1RpUVNnWTAKF8x4WW/xUVY02UhlEfs2kYgZQUW+Rvkr
            N1s7qRjpcq2wDSwPlyrsoRHgzY8VcKWsPYMpwFAAU1kUg/PiXfohyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T00:06:23Z"
    mac: ENC[AES256_GCM,data:ErLRAu5dWVyeaXmmKN5t5tiUnqvQA+akVQbo5CV7rTv/cSDAT/sp4EsCjLaDWd6NPme+hxDX9HcUhelh34lRbMkE+TODwCUrrZHu6bweNz4v/B++rNMCM0wazZQKRgtzFeMZXyGFrkYtgiTBlgTJ3H2v4SMmfjs/8iID1fzIP+w=,iv:ThIvYjWY0+rP8rMa0PxhRC249QiN7pWUsZk8QmW6ftA=,tag:bg2LvD5+cNdtdMdNMhzqtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
