apiVersion: v1
kind: Secret
metadata:
    name: airtrail-db
    namespace: airtrail
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Q+HJtcnF1fA=,iv:m9qsTNNO/eUCKeaGI4Q7oLLUyqkYjHJwwgUJsE5XNa4=,tag:MSu1I5o8lZc7/sOdJOd1rQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Mp5KS1SHAfeLRHKmqVn2kKtv1OyvA5i9m7vgU14iteo=,iv:BM8NZ/n2tqXPKcVbhTUMkrwgTQPih1tf8zyBzsPbFrg=,tag:t6L5wPRfqvk6Bjhz4fZ4sQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:OlZrx/5sqME=,iv:s4EM0lM9LYab2m9FJWt/SLAqZqIuUCgigFnXJ7lifqU=,tag:QP6Aok5Qb9PtKCuECQCeJA==,type:str]
    DB_URL: ENC[AES256_GCM,data:pRJcfTjFO9z0t2feCxgFYaGAbzl/lFf0GT0quZZsZWyoVihlSDyTczJ4Mq53xzoWDVeifCrNF7G8tac4YszKQwgV+V3r1zRDuBSMdghokqHugWX5,iv:ATSJPyZAIlA2la8XhqFvPeg8vmtgNaA1Bv8fODhVEHI=,tag:S5CvertXIaomcy6cQnnI2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUdDVHIwZ0hzb0VmYjFU
            cmNyVzI1dGp3eUhDaXh0eDR0WVVYQWFma0FnCnFtTkNsZURoUVAwcm5maEsxVTdS
            dnVIYnErRGMwMkIxdkdlS1hiSUpKKzgKLS0tIDNaQWNFbWFGaG52aFpTV21qUEZk
            SzdabFgwMVVjaERGU3grRDFkZThicjgKZWQQ+j3OIKdeblhFo3liBJU+b81pcytD
            Gx6VLhmDUIIkXCkhStIQePyeT0bimjJV2Skl2nMaCSwC0WfLxWGPcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T18:50:04Z"
    mac: ENC[AES256_GCM,data:wcg+bkhvnchY0IeRhfKNYNvNekDSVO1UDh5+/xGyfHBuRqMQkImvcJurf761q6wVmqi7PDQOrz1v5jgVZstJmwjnNg7I1fryNFJnMS+upFNQEvcrGrDiOZVsduvbLJFEm1prstWtNkhml82gqpFptfnnJ54gkIUHKmh5vQZxB2Q=,iv:zi3m/UVlKCwbQ6AP041LkKbyDXmvnceq9QrGWDagbso=,tag:DzOHSzbZmiFKmI8KmiW6VA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: airtrail-app
    namespace: airtrail
stringData:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:9HyRipUUEPI22fzfcU2chQ1YcLCi9f1Kurd6LO8NAuQ=,iv:6vi+Es0NbHBAw5bIvQpI2htD9RemJWOcCdHTnAbhEBM=,tag:Wc4tC6MI1YzzZnIdem/+zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVUdDVHIwZ0hzb0VmYjFU
            cmNyVzI1dGp3eUhDaXh0eDR0WVVYQWFma0FnCnFtTkNsZURoUVAwcm5maEsxVTdS
            dnVIYnErRGMwMkIxdkdlS1hiSUpKKzgKLS0tIDNaQWNFbWFGaG52aFpTV21qUEZk
            SzdabFgwMVVjaERGU3grRDFkZThicjgKZWQQ+j3OIKdeblhFo3liBJU+b81pcytD
            Gx6VLhmDUIIkXCkhStIQePyeT0bimjJV2Skl2nMaCSwC0WfLxWGPcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T18:50:04Z"
    mac: ENC[AES256_GCM,data:wcg+bkhvnchY0IeRhfKNYNvNekDSVO1UDh5+/xGyfHBuRqMQkImvcJurf761q6wVmqi7PDQOrz1v5jgVZstJmwjnNg7I1fryNFJnMS+upFNQEvcrGrDiOZVsduvbLJFEm1prstWtNkhml82gqpFptfnnJ54gkIUHKmh5vQZxB2Q=,iv:zi3m/UVlKCwbQ6AP041LkKbyDXmvnceq9QrGWDagbso=,tag:DzOHSzbZmiFKmI8KmiW6VA==,type:str]
    version: 3.13.3
