apiVersion: v1
kind: Secret
metadata:
    name: dawarich-db
    namespace: dawarich
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bFT/xStZ56f9d6jfiA7vVOkZp+upyTp53NXLwdkAHiHhzF8Lg4kQlhW1jMQXN1hY,iv:ueMJXwjabCdUwAB4N5WW9HjgRnqHQJt/Qa/NaxvEgb8=,tag:6G49j7RLvTlEzS3r1utTWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNlZKeFR2ZlZRaEtvdVd0
            WkM5MzJHcTVwaEl1UTNzMHV1ZEtUcDdsY3c4ClpOWnZHc1JoelRZaVZqNHh3ZWNJ
            TFo5VTJQamppTWdKNUxISFZORXlHVDgKLS0tIElTa0NkMFB3RDRvTkdCZ2kwRHNl
            Um9ka3I4LzVpQmM5Q0tkOElQZGYxZjgKg7oivVXzpO6OkPHn4lWLStUi0QvQf1XY
            YoHN9I3ONnw/k/7MnBxMywpABosk1XGcEAF/wAB7dJ8x0SJYnQdvDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:40:05Z"
    mac: ENC[AES256_GCM,data:Zbrt3BhVJt04XzGrZmk9rgItkrTOOicD7v60sNivs8QUvmvdn0ryyuLQTfhuwk4wr+0rUJ7Nw77N8mVsEebHelr+lHzs0IcxoSsen5C07t/VR49QwVW+bc1dk5OwMo1bICWkOwdW9SNuWuIwTcXCojLIq+OVUo0XLtY2bvqoxDA=,iv:saKJOMgnZn3XqAbWnSJAmDi8Ie62eIwVSGFgLz1vS14=,tag:rYI9xsriLJ8lIhfLANteXw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: dawarich-app
    namespace: dawarich
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:xhGy4Ka/MXaTKu4Mmng2Cq5FRy0Elj4zA93KgLDwZNmz7LcYId1xK0sHIIOrWoC0M3le9+infaU16/jUiw2O0gHewfHWsS97mH6qivNdCVFuGWH4T+06AIdGZ7zzbf2d23udkvdK3GVfjwdIn44FHYr37eKLFaCQknyK8lulSZ8=,iv:68IdyYnNjKXR9jlLuZYSEKQhi7HAcAdjqaNqnB2ywK4=,tag:s1VI0ry9uTA+FaVP6MpSwA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3jUgwk06HnoZoTUNNQWTIYUqKQeJGofe3Vn3dvclSFbIkYE6qFY+ZNz5+lVfrKktGBR5K+DF3R2riFcRVJyQqw==,iv:fl1VVNO9klIfby+Bd+iAXtHtZf/vZZ8uJDxXQs2c/74=,tag:N9VhD5lpDWXnLC6iJQZ7pg==,type:str]
    PHOTON_API_KEY: ENC[AES256_GCM,data:qjiCPf/pXTjhxyop3fum1rOPcDuIMpHWuWXy1c9dU5DB8Ns=,iv:AuVPjm67f6hVuupXc/zW1mqZSAyZlk42F6Pzhg5IHj8=,tag:UnLGhoRgjjBpgsJL6QIs7w==,type:str]
    OTP_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:GMroGm9PWdlIeZFiDhwMTTa34ZYElSrP8coe2ZatBcPsbSoRr6A+14/+/GawWhSar5weLPJUGq1+F1kQ9VvqAg==,iv:IZQyBHCT6iimllMs5FVashM8XX4zY6WwszRnDDHTRGU=,tag:LeQ1QtaCxsaZmJgaXlgJaQ==,type:str]
    OTP_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:ExUpArLxXMmJhwxqoL+UC91W0mAQGXUoroxRxhqbdLn1/uJ+E96HT/MprJkBXtTxFPlJNttykeKfeQwrM2p82w==,iv:sVv3AWuP6YC41YycO9F1Mbf32EXS2Nf4WL+0xwbk1QI=,tag:FlpKszB6n4K6rIH8jb9JUg==,type:str]
    OTP_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:fpp6dqUydxIKC4kWbdjy9AbrYrzkQ6L0JzhmhcUHTW41mhKxyWRf3hkU+75qwZyCCMf36WKg3ApFgVbt7uvjEA==,iv:UEXdoz7EqqFZhof8ywt0hCeIxHibRRaYoMyRvYsjmI4=,tag:vFlTpEMxgAcF31Gks1BOrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNlZKeFR2ZlZRaEtvdVd0
            WkM5MzJHcTVwaEl1UTNzMHV1ZEtUcDdsY3c4ClpOWnZHc1JoelRZaVZqNHh3ZWNJ
            TFo5VTJQamppTWdKNUxISFZORXlHVDgKLS0tIElTa0NkMFB3RDRvTkdCZ2kwRHNl
            Um9ka3I4LzVpQmM5Q0tkOElQZGYxZjgKg7oivVXzpO6OkPHn4lWLStUi0QvQf1XY
            YoHN9I3ONnw/k/7MnBxMywpABosk1XGcEAF/wAB7dJ8x0SJYnQdvDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:40:05Z"
    mac: ENC[AES256_GCM,data:Zbrt3BhVJt04XzGrZmk9rgItkrTOOicD7v60sNivs8QUvmvdn0ryyuLQTfhuwk4wr+0rUJ7Nw77N8mVsEebHelr+lHzs0IcxoSsen5C07t/VR49QwVW+bc1dk5OwMo1bICWkOwdW9SNuWuIwTcXCojLIq+OVUo0XLtY2bvqoxDA=,iv:saKJOMgnZn3XqAbWnSJAmDi8Ie62eIwVSGFgLz1vS14=,tag:rYI9xsriLJ8lIhfLANteXw==,type:str]
    version: 3.13.3
