apiVersion: v1
kind: Secret
metadata:
    name: dawarich-db
    namespace: dawarich
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:u2sjFNHdzHtIsaWiNaNsXAoNhxbj46Ads9X64ME9MR0mYr+PO8D+0LPgpOpBPWaH,iv:lN7Fsb/My+Ej7JNu6FikHCsGxqoY+rQ8WYQiDVptJ4k=,tag:TtYZfSjDaj9iYRMMO0vVHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NWRsTFlML05vbHJJbkt3
            VHdtcXhnZzhJYUs1RnU1Vk5CQWluOHZadEhVClRIRTR4K0lHbmpQdGdRc1VyUWxS
            dVZRMWkyZEthVVNGaVVLUlhqT0dRb2MKLS0tIHZITDBZSGE4ZGdFN3drOWJaZEl0
            WnkyYWYvNWk4eHNyUitiRCtBRG02cTQKc9M3BfcNzTIjelyqaEfUtQsBFDlEVHyF
            UBfWdPXWgkUME19Yvvvzbl65TIFVGYkvhMTZ+GPYFF0EP969WfWPXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T18:32:29Z"
    mac: ENC[AES256_GCM,data:p/hMt9bCeVVWaVyAT/nPJSE8E5A1Fg4U2LokMNjf6nIH0tw5kEbCNVt/qw/slqyr2smD9k+vNfEd4sfuxzdRHwZm0j24Dozpl2MUWLSjDzzdSK2swE1My2em7wQU5NpJcY7Dqj5X1adaBGH3Dq96jUwGK6p1+BvyoLod5KkndMc=,iv:kJQRsBXnienpOwBIw+ZlzBAAyViFTGZEDye+sXu7Er4=,tag:aVm7S5pFuM/WwKRLmJazbQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: dawarich-app
    namespace: dawarich
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:qiMqZo/w3EmRR17DTBbbUP+E0B8/UJPm0wWRo9jjAbrLZ//c9s9eMgpkxBjJrFLW/BKAOu0HVQFLPmlu0WD0bo2xgh3WcWCjBOuLvoZvGLm4F7DrCWJZXAr85yZaQvMv4vcNHTMy4FXX6iqucjX1rYvmEQlnBi19fWUk+ZWd3YM=,iv:RorqVfTn4+4AYw2mZrxjIk0IirumLoae+1msUMKQkJQ=,tag:ps9uDDwjHvHaFSjUGcX6xw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/cMFSR2VEFmfvrilrV4Wu0vgl5JB63iV8hx0HvsXPmcuLRyODM38E3fLd/WrofEHM9wvqah9qf0mxVJ2YUKZAA==,iv:PpUHHdFyN3Nzn1eON1l97hNa2R1dQOO5ejMgENKqMZA=,tag:DtJjPTCLTLAvw8G79AZuMg==,type:str]
    PHOTON_API_KEY: ENC[AES256_GCM,data:M6fNZhc4z66nDnmMu8n/yT+zJ+ZscmxAX/UQ2ukG3PkdKrY=,iv:ZQTLi+NdPfdehXGKF9PIzg0yAy0xD9CfAwuROps/Xo4=,tag:3QliuKCx0nUO1FD69R03IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NWRsTFlML05vbHJJbkt3
            VHdtcXhnZzhJYUs1RnU1Vk5CQWluOHZadEhVClRIRTR4K0lHbmpQdGdRc1VyUWxS
            dVZRMWkyZEthVVNGaVVLUlhqT0dRb2MKLS0tIHZITDBZSGE4ZGdFN3drOWJaZEl0
            WnkyYWYvNWk4eHNyUitiRCtBRG02cTQKc9M3BfcNzTIjelyqaEfUtQsBFDlEVHyF
            UBfWdPXWgkUME19Yvvvzbl65TIFVGYkvhMTZ+GPYFF0EP969WfWPXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T18:32:29Z"
    mac: ENC[AES256_GCM,data:p/hMt9bCeVVWaVyAT/nPJSE8E5A1Fg4U2LokMNjf6nIH0tw5kEbCNVt/qw/slqyr2smD9k+vNfEd4sfuxzdRHwZm0j24Dozpl2MUWLSjDzzdSK2swE1My2em7wQU5NpJcY7Dqj5X1adaBGH3Dq96jUwGK6p1+BvyoLod5KkndMc=,iv:kJQRsBXnienpOwBIw+ZlzBAAyViFTGZEDye+sXu7Er4=,tag:aVm7S5pFuM/WwKRLmJazbQ==,type:str]
    version: 3.13.3
