apiVersion: v1
kind: Secret
metadata:
    name: norish-db
    namespace: norish
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:a1a6kFbv,iv:gndSyeMEA7QbSaqpt1Htjt9FPm+Lw5VXlN/wc2MbffM=,tag:2EKw2yy/nB0Vrtvdow9grQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LH5UNhzASHikoOO5xSDdYEgMk/sJZLbUkxc8/2Kasz83S/CU4N9uS87QQ6Tv7hq0,iv:hEffIcrC+mlZiOQypEgo/sDOOTX8o5JlguC03zIudJs=,tag:BR4O+phAHhvOwOnoxqOAMA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:b2wPcDfc,iv:en88U1LsSBUmGjG9tAP8rLFeRYSj7dDFcMtat1GxuTc=,tag:BocnLVarKlopcq3DunQvqQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:n7phHqY4qkZCNksmgmTSWh19EOn0AskxvWXpOsjY6Uha0ujp2MgpEq29FxLsxiphKVBaEsvTneZJ2gG5clacDRRedlOsKnDBJbikrL74NVn7kju1Hi4cqygJoEaYPw==,iv:RvOpqU3CXL0YMvgQ97Q/TLZ3U9vnRBWqbyXQu6GgmiM=,tag:CWsmuDijixQFJ4XLbwPbVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeHl5Z0tlNDdacWU2M3ZG
            aWdDOFFGMURRNTA0QTJnTHNEYWVieHFPZFZ3CjVMTWt3bEM4VnhpdUJSS3FTVXVI
            NlhXM0MrRjFqcW9OZ2tUK1N4QVpYV2cKLS0tIHp3cnp2a1lhTmFQVmdTbUFaZGJG
            SXgvUnYrc1ZRN25UQ3M0K3VGWjV4Y28Knq0YlU4LU7Sosjc+3FVHdiTotsaqdPcS
            AEBuI5xfEsBoKke2jGLlizYnNDIOukcXv2B0/mcKWXHWyDQjQa+fOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T18:39:43Z"
    mac: ENC[AES256_GCM,data:YI7jQLAK69R0t3HOl+0SQIJteDbCLDk8mD9Ljlu2e8AuCRNuO+YDe4/LRlqbhs6+jFSVQCk/4fnBLvWbdY3tWVj0UnqTbWl2uB4I9sXpkw3+8w/Dn6F5hOLyQD6lxYlVmrbQdaTCiLoeuwBihvUfrWUkwhiJk607nigNR1mrzp0=,iv:x4xCWpQjgJkF76Pphmgis+V3q+sY49lN844m08/AuN8=,tag:7fqriYAchanUIkUDmjxLzA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: norish-app
    namespace: norish
stringData:
    MASTER_KEY: ENC[AES256_GCM,data:Q8pnAjJaboFZto81Y87IQV+lRuiR7rcqFB29uFVhbHbWuxWKeSl5t0Hm4Hg=,iv:SSqXsH62BPTDcbNNGLxJJh5z+V1ZTKmrDoi8rwO/DIs=,tag:cPiKs7M3xsp9K6kNgp1qQg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:E2rIJg1z0WW8lt8RMvtqTKDGQIhBt4lSwHvQP9vs1vaqheXKqFnNVYfmhT9UI1SrDEKifCswd50GbDJZwoKajw==,iv:WDM6R/OD9vl/Vn50Xvaoy7o5q8yVLmW9g2sxG6SGkUE=,tag:/tU5bVkJeaiTBa+yGnAzag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeHl5Z0tlNDdacWU2M3ZG
            aWdDOFFGMURRNTA0QTJnTHNEYWVieHFPZFZ3CjVMTWt3bEM4VnhpdUJSS3FTVXVI
            NlhXM0MrRjFqcW9OZ2tUK1N4QVpYV2cKLS0tIHp3cnp2a1lhTmFQVmdTbUFaZGJG
            SXgvUnYrc1ZRN25UQ3M0K3VGWjV4Y28Knq0YlU4LU7Sosjc+3FVHdiTotsaqdPcS
            AEBuI5xfEsBoKke2jGLlizYnNDIOukcXv2B0/mcKWXHWyDQjQa+fOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T18:39:43Z"
    mac: ENC[AES256_GCM,data:YI7jQLAK69R0t3HOl+0SQIJteDbCLDk8mD9Ljlu2e8AuCRNuO+YDe4/LRlqbhs6+jFSVQCk/4fnBLvWbdY3tWVj0UnqTbWl2uB4I9sXpkw3+8w/Dn6F5hOLyQD6lxYlVmrbQdaTCiLoeuwBihvUfrWUkwhiJk607nigNR1mrzp0=,iv:x4xCWpQjgJkF76Pphmgis+V3q+sY49lN844m08/AuN8=,tag:7fqriYAchanUIkUDmjxLzA==,type:str]
    version: 3.13.3
