apiVersion: v1
kind: Secret
metadata:
    name: mindwtr-auth
    namespace: mindwtr
stringData:
    token: ENC[AES256_GCM,data:KOMG/h2TTKH99qwhJgkYn4ADdOHTILzvCpej1YK68JT88hQ8MjKSir/0qPo6h0nc/zhWRGPgxUG3akWKcsZekQ==,iv:jYgI6Vh3JTqPUyMbem3JmSh25rAbzgauaBo79vzfSSs=,tag:Rj2Cls74d6CSoIPZUkgZ5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNUhjelJtcWkvMlFlZVVK
            YWdja1F6TVNzQjlsbFhhbjJzQ2RtYytxZ3dvCm8vR3NHWkFraVFpa2hoVTNkSVhh
            amZMV3pVY1Z1NkZPYzZ0bEllUkxaeUEKLS0tIEFWcnVTOVdPYjJVUTlGYVFsRGl3
            TGJLd0pDbUdxZzhiMVZXZ1VpYkIycE0KjjbK3F8J45ybUxmdLBDKrfHjccIP84k0
            kNRAyT3Oqv6xhVAGbDhLjTfvGuKf67+4FXNt/KZi83cwcnfnr9RLSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T18:22:12Z"
    mac: ENC[AES256_GCM,data:DTY0Iu42hcW5iGx8sYIbVZ+pmr26pnVbkU8ypwCjgWwM5xQeIOGgKzk4IaMN9IlzUlXPmjGjRyb8E37izHrIjJSwCL9+7VskFtzY/h1mtodDFeWzkbXaPdifv3IEKTwxtmA+QrWiwwwbongfOOk2M4LHHLikZN8/gkbjwzllVTs=,iv:MQGIukiR9/txUOAeBH0yGT3JOoi0nYrl6TJPpYyStVE=,tag:PDZ7/dh/hxKlyuRykvZh/Q==,type:str]
    version: 3.13.3
