apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actualbudget
  - authelia
  - bentopdf
  - dnsproxy
  - dozzle
  - immich
  - it-tools
  - linkding
  - lldap
  - ntfy
  - silverbullet
  - tss
