apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:fK2Z+fQap7goFVgU0Z7zWBoRSj7hx/Q7rv6VTqfYu52gCp/jLzl8oA==,iv:UJlhiRkyC+CqxMwZI+40HTwd90acfn8FbDvB8llLCRE=,tag:AESRDHKJYvyLAocbdfOJXQ==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeVlsR1cwTnE4MnlhNHVi
            QXhlRDJ2SHFjQUtHSlp3ZW9DSUxxWTVoaFZ3CkhTUHRmYnQ3SG12Z0pudDkydVQ2
            ZHhtNnBxNXB0Zkg3dmFxMXgyMkt5dWcKLS0tIDhjbzVmUzdPdlB3T0NsNVhucXdy
            UkFCcVp6NVYweERMQmJBWVlpbFpJVTAKyjEu5retI6KBO249qFcrEvRgoAG7HlQg
            T43c7fmaGK5ZuK/GudJDVE2t/aOyz1k4hHt6QWT0ipEHB/EH6lCvGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T00:06:23Z"
    mac: ENC[AES256_GCM,data:DiWUeWbqGkzYKS+x0RtwDp/OFQ63ttGhW4Q2z1IEd7MdxRbU8i6SiOjx+YMHvUtWRlWJM7JXAlXr5r+boATpBP5US9RYAmEhk3tUOK2T3eOL2UDmqLRQX+oMF+atLXEvTplM6dBIEQmmvyGgVEznG8JyvK2Hyr3v3GBghx0hynQ=,iv:+yOzIKA3DRRjeklYX5GUZlOhIXRmpYrp2a/KbZHPJ7o=,tag:7kZAQw6mfInZ5da6Sv3o0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
