apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: actual-budget
  namespace: traefik
spec:
  entryPoints:
    - frp
  routes:
    - match: Host(`budget.${DOMAIN}`)
      kind: Rule
      middlewares:
        - name: frp-headers
          namespace: traefik
      services:
        - name: actual-budget
          port: 80
          namespace: actual-budget
