apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-budget-pv
  namespace: actual-budget
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/data/actualbudget"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-pvc
  namespace: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
