apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: actual-budget-secrets
    namespace: actual-budget
stringData:
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:yCe6mwBL/50NLqm/T9vPZGDZ3H9nHPY6UIynomeKsFYjCwEQnqzmiXxsQ5iRqzuPTJ15NovCEMZp/3fVhzgHpikrCT8QGv/c,iv:1paGLkIuWLjJ6jBebOd7wVPiQOE36d9yTN9Y/KQiq+c=,tag:iuOru3U5Rf5CWdg/BE1TLg==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Mlo1TnpDVVlrWUN2Sy9v
            Nm5KWWE5QmVFbGVseStFbE82Q2cySTdVWkYwCkQrQW9WS0EwU0ZmdDJwM1NrZzg1
            UGZtU3Bmb2FHMG5rdnp1alBiOFk3TEEKLS0tIFBWZmdVOUJ0V0gzTm9tRmd1dGVV
            ckN3UldNNGNydVJiV3RBa0JzRmllK0kK/oKATdTVLLgyQzJi+sQxHhTI9OR0jMXy
            A4KQfad2EtdX6EXBzrQUljeo+DjG2IbcCbK1ejaVbvboLhoRN/G/pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T20:37:32Z"
    mac: ENC[AES256_GCM,data:9nlOtm4m7M8boHoDqyLJs9knHK0GTZ5rCcQ8UNiW+AqtfR1BXtvNaGaStYCfRZRMPUqGjNHQnbqV88zkSzapyFtlf3O6teQLG35rt8xL06BQyvVRD3CJXkNRFVvSMr+RAWkhl66A2dbVf+YPEnp47EwOpMV7+2qSkyRkAYDohb8=,iv:V4ldxF5nhu7iCecAD0O3ZZDljSDFkXwCEfWv0enEa3w=,tag:I9f3ezXnLJfLH4chN4xCAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
