apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverbullet
  namespace: silverbullet
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: silverbullet
  template:
    metadata:
      labels:
        app: silverbullet
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: silverbullet
          image: ghcr.io/silverbulletmd/silverbullet:2.6.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: SB_HOSTNAME
              value: "0.0.0.0"
            - name: SB_USER
              valueFrom:
                secretKeyRef:
                  name: silverbullet-user
                  key: sb-user
            - name: SB_INDEX_PAGE
              value: "Home"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: silverbullet-data
              mountPath: /space
      volumes:
        - name: silverbullet-data
          persistentVolumeClaim:
            claimName: silverbullet-pvc
