apiVersion: v1
kind: PersistentVolume
metadata:
  name: silverbullet-pv
  namespace: silverbullet
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: "/data/silverbullet"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silverbullet-pvc
  namespace: silverbullet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
