apiVersion: v1
kind: Secret
metadata:
    name: silverbullet-user
    namespace: silverbullet
data:
    sb-user: ENC[AES256_GCM,data:HlkzXAx4f3NUPbwuJ5C/DlwXvcWXxgetlifPhGgozpKzTcBaaLlLYw==,iv:YZsvuAXBWvBi8OoD2Jx8zC53qDbqlCF+DvPeWYBl3k4=,tag:uxvWRXdagYa3swSlWQx2/w==,type:str]
sops:
    age:
        - recipient: age16kdplzy6q4sgyzr88ufzq9zwj6lz60rkq9pqlm7y26g8hpweps4s2wqs2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRVlHWTJ2NklpV0E4UkE2
            UGFWTnBnSkNUTVA3WFgrTnhra2xZYWRPSkhRCkdyaW1QeTZ3a2JPL2NxdFBtSE9z
            cWxWUkNiUzZYZmJobXNpUk91Yk1aRHMKLS0tIFhpTG9PSFFVWXlHcFYrZWhsWklV
            d2VqdFhYV0duMXU0OElvNDY1Y0JLQVkKA3ZuWjadd+epDDX0LhFo6uEZ9jbxwogV
            kqE/0CGqRo1nrdk1hQfZbN8cm+jMJSOzFNqbe44WRVJGMcV162gxsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T20:37:44Z"
    mac: ENC[AES256_GCM,data:N3fXNrIcCCQnrTEh7bIRKU/MCDZ/cDUbzg0mUUYBDIwhYTR5XC9QY/XCL8XJrWvm2PF/HW1jds2BUdUhHSU9YtL0nPs4rVXbS/E2iMYhspgE2aDAAFdvm4dt47ooXgLddf7ZYSGwMfjQWTKDAWgcYFLG588X8noUTyf9bxOXjG4=,iv:zO9hY1JjZn7XmMHmvH3OK+a2X8UDA51/EOw2NjXg4YU=,tag:Pzt0JwjT7Dw7cvtEUNcI6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
